CREATE TABLE eligiblevoters (
voterid int primary key,
county text,
first_name text,
middle_name text,
last_name text,
suffix text,
birth_date date,
registration_date date,
address_1 text,
address_2 text,
city text,
state text,
zip text,
phone text,
party text,
congressional_district text,
senate_district text,
assembly_district text,
education_district text,
regent_district text,
registered_precinct text,
county_status text,
county_voter_id text,
id_required text
)
